use crate::Draw;

pub enum ASCII {
    Space,
    ExclamationMark,
    QuotationMark,
    NumberSign,
    DollarSign,
    PercentSign,
    Ampersand,
    Apostrophe,
    LeftParenthesis,
    RightParenthesis,
    Asterisk,
    PlusSign,
    Comma,
    Hyphen,
    Period,
    Slash,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Colon,
    Semicolon,
    LessThan,
    EqualsTo,
    GreaterThan,
    QuestionMark,
    AtSign,
    UppercaseA,
    UppercaseB,
    UppercaseC,
    UppercaseD,
    UppercaseE,
    UppercaseF,
    UppercaseG,
    UppercaseH,
    UppercaseI,
    UppercaseJ,
    UppercaseK,
    UppercaseL,
    UppercaseM,
    UppercaseN,
    UppercaseO,
    UppercaseP,
    UppercaseQ,
    UppercaseR,
    UppercaseS,
    UppercaseT,
    UppercaseU,
    UppercaseV,
    UppercaseW,
    UppercaseX,
    UppercaseY,
    UppercaseZ,
    LeftSquareBracket,
    Backslash,
    RightSquareBracket,
    Caret,
    Underscore,
    GraveAccent,
    LowercaseA,
    LowercaseB,
    LowercaseC,
    LowercaseD,
    LowercaseE,
    LowercaseF,
    LowercaseG,
    LowercaseH,
    LowercaseI,
    LowercaseJ,
    LowercaseK,
    LowercaseL,
    LowercaseM,
    LowercaseN,
    LowercaseO,
    LowercaseP,
    LowercaseQ,
    LowercaseR,
    LowercaseS,
    LowercaseT,
    LowercaseU,
    LowercaseV,
    LowercaseW,
    LowercaseX,
    LowercaseY,
    LowercaseZ,
    LeftCurlyBrace,
    VerticalBar,
    RightCurlyBrace,
    Tilde,
}

impl Draw for ASCII {
    fn draw(&self, target: &mut crate::View) {
        match self {
            ASCII::Space => todo!(),
            ASCII::ExclamationMark => todo!(),
            ASCII::QuotationMark => todo!(),
            ASCII::NumberSign => todo!(),
            ASCII::DollarSign => todo!(),
            ASCII::PercentSign => todo!(),
            ASCII::Ampersand => todo!(),
            ASCII::Apostrophe => todo!(),
            ASCII::LeftParenthesis => todo!(),
            ASCII::RightParenthesis => todo!(),
            ASCII::Asterisk => todo!(),
            ASCII::PlusSign => todo!(),
            ASCII::Comma => todo!(),
            ASCII::Hyphen => todo!(),
            ASCII::Period => todo!(),
            ASCII::Slash => todo!(),
            ASCII::Digit0 => todo!(),
            ASCII::Digit1 => todo!(),
            ASCII::Digit2 => todo!(),
            ASCII::Digit3 => todo!(),
            ASCII::Digit4 => todo!(),
            ASCII::Digit5 => todo!(),
            ASCII::Digit6 => todo!(),
            ASCII::Digit7 => todo!(),
            ASCII::Digit8 => todo!(),
            ASCII::Digit9 => todo!(),
            ASCII::Colon => todo!(),
            ASCII::Semicolon => todo!(),
            ASCII::LessThan => todo!(),
            ASCII::EqualsTo => todo!(),
            ASCII::GreaterThan => todo!(),
            ASCII::QuestionMark => todo!(),
            ASCII::AtSign => todo!(),
            ASCII::UppercaseA => todo!(),
            ASCII::UppercaseB => todo!(),
            ASCII::UppercaseC => todo!(),
            ASCII::UppercaseD => todo!(),
            ASCII::UppercaseE => todo!(),
            ASCII::UppercaseF => todo!(),
            ASCII::UppercaseG => todo!(),
            ASCII::UppercaseH => todo!(),
            ASCII::UppercaseI => todo!(),
            ASCII::UppercaseJ => todo!(),
            ASCII::UppercaseK => todo!(),
            ASCII::UppercaseL => todo!(),
            ASCII::UppercaseM => todo!(),
            ASCII::UppercaseN => todo!(),
            ASCII::UppercaseO => todo!(),
            ASCII::UppercaseP => todo!(),
            ASCII::UppercaseQ => todo!(),
            ASCII::UppercaseR => todo!(),
            ASCII::UppercaseS => todo!(),
            ASCII::UppercaseT => todo!(),
            ASCII::UppercaseU => todo!(),
            ASCII::UppercaseV => todo!(),
            ASCII::UppercaseW => todo!(),
            ASCII::UppercaseX => todo!(),
            ASCII::UppercaseY => todo!(),
            ASCII::UppercaseZ => todo!(),
            ASCII::LeftSquareBracket => todo!(),
            ASCII::Backslash => todo!(),
            ASCII::RightSquareBracket => todo!(),
            ASCII::Caret => todo!(),
            ASCII::Underscore => todo!(),
            ASCII::GraveAccent => todo!(),
            ASCII::LowercaseA => todo!(),
            ASCII::LowercaseB => todo!(),
            ASCII::LowercaseC => todo!(),
            ASCII::LowercaseD => todo!(),
            ASCII::LowercaseE => todo!(),
            ASCII::LowercaseF => todo!(),
            ASCII::LowercaseG => todo!(),
            ASCII::LowercaseH => todo!(),
            ASCII::LowercaseI => todo!(),
            ASCII::LowercaseJ => todo!(),
            ASCII::LowercaseK => todo!(),
            ASCII::LowercaseL => todo!(),
            ASCII::LowercaseM => todo!(),
            ASCII::LowercaseN => todo!(),
            ASCII::LowercaseO => todo!(),
            ASCII::LowercaseP => todo!(),
            ASCII::LowercaseQ => todo!(),
            ASCII::LowercaseR => todo!(),
            ASCII::LowercaseS => todo!(),
            ASCII::LowercaseT => todo!(),
            ASCII::LowercaseU => todo!(),
            ASCII::LowercaseV => todo!(),
            ASCII::LowercaseW => todo!(),
            ASCII::LowercaseX => todo!(),
            ASCII::LowercaseY => todo!(),
            ASCII::LowercaseZ => todo!(),
            ASCII::LeftCurlyBrace => todo!(),
            ASCII::VerticalBar => todo!(),
            ASCII::RightCurlyBrace => todo!(),
            ASCII::Tilde => todo!(),
        }
    }
}

impl Draw for String {
    fn draw(&self, target: &mut crate::View) {
        todo!()
    }
}
